# Generated by Django 3.0.8 on 2020-07-23 21:40

import buckets.models
from django.db import migrations, models
import django.db.models.deletion
import project.storage_backends


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='FSObject',
            fields=[
                ('object_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='project.Object')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='buckets.FSObject')),
            ],
            options={
                'abstract': False,
            },
            bases=('project.object',),
        ),
        migrations.CreateModel(
            name='Bucket',
            fields=[
                ('fsobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='buckets.FSObject')),
            ],
            options={
                'abstract': False,
            },
            bases=('buckets.fsobject',),
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('fsobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='buckets.FSObject')),
                ('format', models.CharField(choices=[(0, buckets.models.File.Format['undefined']), (1, buckets.models.File.Format['pdf'])], default=None, max_length=3, null=True)),
                ('_path', models.FileField(storage=project.storage_backends.StaticStorage(), upload_to='')),
                ('_instance', models.FileField(null=True, storage=project.storage_backends.MediaStorage(), upload_to='')),
            ],
            options={
                'abstract': False,
            },
            bases=('buckets.fsobject',),
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('fsobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='buckets.FSObject')),
            ],
            options={
                'abstract': False,
            },
            bases=('buckets.fsobject',),
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='buckets.File')),
            ],
            options={
                'abstract': False,
            },
            bases=('buckets.file',),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='buckets.File')),
            ],
            options={
                'abstract': False,
            },
            bases=('buckets.file',),
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='buckets.File')),
            ],
            options={
                'abstract': False,
            },
            bases=('buckets.file',),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='buckets.File')),
            ],
            options={
                'abstract': False,
            },
            bases=('buckets.file',),
        ),
    ]
