# Generated by Django 3.0.8 on 2020-07-16 03:20

from django.db import migrations, models
import project.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='_instance',
            field=models.FileField(storage=project.storage_backends.MediaStorage(), upload_to=''),
        ),
    ]
