# Generated by Django 3.0.7 on 2020-06-28 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0001_initial'),
        ('buckets', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Page',
            new_name='Text',
        ),
        migrations.RemoveField(
            model_name='text',
            name='object_ptr',
        ),
        migrations.AddField(
            model_name='text',
            name='file_ptr',
            field=models.OneToOneField(auto_created=True, default='', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='buckets.File'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fsobject',
            name='parent',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='buckets.FSObject'),
            preserve_default=False,
        ),
    ]
