# Generated by Django 3.0.7 on 2020-06-28 18:23

import buckets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0002_auto_20200628_0506'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='format',
            field=models.CharField(choices=[(0, buckets.models.File.Format['undefined']), (1, buckets.models.File.Format['pdf'])], default=None, max_length=3, null=True),
        ),
    ]
