# Generated by Django 3.0.7 on 2020-06-28 19:02

from django.db import migrations, models
import project.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0003_file_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='path',
            field=models.FileField(default='', storage=project.storage_backends.StaticStorage(), upload_to=''),
            preserve_default=False,
        ),
    ]
