# Generated by Django 3.0.7 on 2020-06-26 02:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_documentbinaryclassification'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DocumentBinaryClassification',
            new_name='BinaryClassification',
        ),
        migrations.AlterField(
            model_name='job',
            name='tag',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='progressreport',
            name='tag',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
