# Generated by Django 3.0.7 on 2020-06-26 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20200626_0222'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BinaryClassification',
            new_name='Classification',
        ),
    ]
