# Generated by Django 3.0.7 on 2020-06-26 06:58

from django.db import migrations, models
import django.db.models.deletion
import jobs.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_account'),
        ('jobs', '0006_job_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.Profile'),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[(0, jobs.models.Job.Status['UNKNOWN']), (1, jobs.models.Job.Status['CREATED']), (2, jobs.models.Job.Status['PENDING']), (3, jobs.models.Job.Status['STARTED']), (4, jobs.models.Job.Status['COMPLETE'])], default='UN', max_length=2),
        ),
    ]
