language: python
python:
- 3.7.7
addons:
  postgresql: '9.4'
before_install:
- openssl aes-256-cbc -K $encrypted_beb0f46490a6_key -iv $encrypted_beb0f46490a6_iv
  -in private.py.enc -out project/settings/private.py -d
- pip install coverage
- pip install coveralls
install:
- pip install -r requirements/dev.txt
before_script:
- createdb -U postgres project
- createuser -U postgres --superuser root
script:
- coverage run manage.py test --verbosity=2 
after_success:
- coveralls
notifications:
  email: false
sudo: false
env:
- DJANGO_SETTINGS_MODULE=project.settings.dev
