language: python
python:
- 3.7.7
addons:
  apt:
    packages:
      - docker-ce
before_install:
- openssl aes-256-cbc -K $encrypted_beb0f46490a6_key -iv $encrypted_beb0f46490a6_iv
  -in private.py.enc -out project/settings/private.py -d
#- pip install coverage
#- pip install coveralls
install:
- pip install -r requirements/dev.txt
before_script:
- docker-compose up
#- createdb -U postgres project
#- createuser -U postgres --superuser root
script:
- docker-compose exec -it backend coverage run manage.py test --verbosity=2 
after_success:
- docker-compose exec -it backend coveralls
notifications:
  email: false
sudo: false
env:
- DJANGO_SETTINGS_MODULE=project.settings.dev
