# Generated by Django 3.0.8 on 2020-07-24 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='BusinessClient',
        ),
    ]
