# Generated by Django 3.0.7 on 2020-06-25 18:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=127)),
                ('index', models.IntegerField(null=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
