# Generated by Django 3.0.7 on 2020-06-26 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='description',
        ),
        migrations.RemoveField(
            model_name='label',
            name='index',
        ),
        migrations.RemoveField(
            model_name='label',
            name='name',
        ),
        migrations.AddField(
            model_name='label',
            name='data',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
