# Generated by Django 3.0.7 on 2020-06-26 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
        ('classifiers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ML',
            fields=[
                ('tool_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tools.Tool')),
            ],
            options={
                'abstract': False,
            },
            bases=('tools.tool',),
        ),
    ]
