# Generated by Django 3.0.7 on 2020-07-01 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classifiers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classifier',
            name='seed',
        ),
    ]
