# Generated by Django 3.0.7 on 2020-07-14 18:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('classifiers', '0002_remove_classifier_seed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classifier',
            name='samples',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
