# Generated by Django 3.0.7 on 2020-06-29 02:35

from django.db import migrations, models
import django.db.models.deletion
import project.storage_backends


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buckets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('fsobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='buckets.FSObject')),
            ],
            options={
                'abstract': False,
            },
            bases=('buckets.fsobject',),
        ),
        migrations.CreateModel(
            name='NLP',
            fields=[
                ('tool_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tools.Tool')),
            ],
            options={
                'abstract': False,
            },
            bases=('tools.tool',),
        ),
        migrations.CreateModel(
            name='TfIDF',
            fields=[
                ('tool_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tools.Tool')),
                ('_vectorizer', models.FileField(storage=project.storage_backends.StaticStorage(), upload_to='')),
            ],
            options={
                'abstract': False,
            },
            bases=('tools.tool',),
        ),
    ]
