# Generated by Django 3.0.7 on 2020-06-29 01:52

from django.db import migrations, models
import django.db.models.deletion
import project.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NLP',
            fields=[
                ('tool_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tools.Tool')),
            ],
            bases=('tools.tool',),
        ),
        migrations.CreateModel(
            name='TfIDF',
            fields=[
                ('tool_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tools.Tool')),
                ('_vectorizer', models.FileField(storage=project.storage_backends.StaticStorage(), upload_to='')),
            ],
            bases=('tools.tool',),
        ),
    ]
